language: c
compiler: gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-transport-https
    - echo "deb https://kdudka.fedorapeople.org/csbuild precise contrib" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq -y --force-yes csbuild
    - sudo apt-get install libcap-dev libncurses5-dev texi2html texinfo

script:
    - csbuild --git-commit-range "$TRAVIS_COMMIT_RANGE" --build-cmd "git clean -xfd && autoreconf -v && ./configure && make" --git-bisect --added-exit-code 7
